In [6]:
import numpy as np
matrice1=np.array([[1,5,9,8],[7,5,3,2]])
matrice2=np.array([1,2,3,4],ndmin=2)
print("first matrice is: ",matrice1)
print("second matrice is:",matrice2)
sum_matrice=matrice1+matrice2
print("the sum of two matrices is : ",sum_matrice)

first matrice is:  [[1 5 9 8]
 [7 5 3 2]]
second matrice is: [[1 2 3 4]]
the sum of two matrices is :  [[ 2  7 12 12]
 [ 8  7  6  6]]


In [ ]:
2.Write a Python Program to Multiply Two Matrices?

In [11]:
import numpy as np
matrice1=np.array([[1,5],[7,5]])
matrice2=np.array([[1,2,7,9],[4,7,5,4]])
print("first matrice is: ",matrice1)
print("second matrice is:",matrice2)
mul_matrices=matrice1@matrice2               # '*'  ==> it gives matrice element wise multiplication 
print("the multiplication of two matrices is : ",mul_matrices)#'@' ===> it gives matrices multipication

first matrice is:  [[1 5]
 [7 5]]
second matrice is: [[1 2 7 9]
 [4 7 5 4]]
the multiplication of two matrices is :  [[21 37 32 29]
 [27 49 74 83]]


In [17]:
import numpy as np
matrice=np.array([[4,5,6,7],[8,9,6,5]])
print("the given matricee is: ",matrice)
trans=matrice.T
print("the transpose of above matrice is: ",trans )

the given matricee is:  [[4 5 6 7]
 [8 9 6 5]]
the transpose of above matrice is:  [[4 8]
 [5 9]
 [6 6]
 [7 5]]


In [19]:
list=['rat','mat','sat,','bat','what','cat','kit']
list.sort()
print(list)

['bat', 'cat', 'kit', 'mat', 'rat', 'sat,', 'what']


In [38]:
string="how was the day?"
new_string=string.replace('?','')
print(new_string)
#another way
import string
str1="hello, what a match!,is it masti?"
for character in string.punctuation:
    str1=str1.replace(character,'')
print(str1)

how was the day
hello what a matchis it masti


In [39]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'